import { Inter } from "next/font/google";

// import "./globals.css";

import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import FooterBody from "@/components/footer/makeFooter";


import ReduxProvider from "@/components/reduxProvider/reduxProvider";
import Header from "@/components/header/makeHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   
    <html lang="en">
      
      <head>
      
        	 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"/>
           
      </head>
      
      <body  className={inter.className}>
        <ReduxProvider>
          <Header></Header>
        </ReduxProvider>
     

         {/* s redux k andr ab sarah children ka data gire ga */}
        <ReduxProvider>
          {children}

        </ReduxProvider>

        
       
        <ToastContainer></ToastContainer>
        <FooterBody ></FooterBody>
        </body>
    </html>
    
  );
}
